:-(dynamic(/('$list#0._ddef',3))).
'$list#0._dcl'(append(_,_,_),p(p(p)),no,0).
'$list#0._dcl'(length(_,_),p(p(p)),no,0).
'$list#0._dcl'(member(_,_),p(p(p)),no,0).
:-('$list#0._dcl'(A,B,C,D,list,list),'$list#0._dcl'(A,B,C,D)).
'$list#0._def'(append(A,B,C),D,'$list#0.append#3'(A,B,C,D)).
'$list#0._def'(length(A,B),C,'$list#0.length#2'(A,B,C)).
'$list#0._def'(length(A,B,C),D,'$list#0.length#3'(A,B,C,D)).
'$list#0._def'(member(A,B),C,'$list#0.member#2'(A,B,C)).
:-('$list#0._def'(A,c(list,list,B),C,list,list),'$list#0._def'(A,c(list,list,B),C)).
:-('$list#0._def'(A,c(list,list,B),C,list,list),'$list#0._ddef'(A,c(list,list,B),C)).
:-('$list#0._super'(_,_,_,_,_),fail).
'$list#0._alias'(_,A,A).
'$list#0.append#3'([],A,A,_).
:-('$list#0.append#3'('.'(A,B),C,'.'(A,D),E),'$list#0.append#3'(B,C,D,E)).
:-('$list#0.length#2'(A,B,C),'$list#0.length#3'(A,0,B,C)).
'$list#0.length#3'([],A,A,_).
:-('$list#0.length#3'('.'(_,A),B,C,D),','(is(E,+(B,1)),'$list#0.length#3'(A,E,C,D))).
'$list#0.member#2'(A,'.'(A,_),_).
:-('$list#0.member#2'(A,'.'(_,B),C),'$list#0.member#2'(A,B,C)).
